Repository ArkEcosystem/cpp-client, pull requests merged in 2019-02, with the labels that each got.

#67 misc: add Arduino Sketch path to Library Config
  library.json
Labels: Status: Contributor Approved

#69 fix: library config examples' paths
  library.json
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Bugfix

#70 fix: Remove Unneeded/Redundant Manifest Fields
  library.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#74 chore: setup code owners
  CODEOWNERS
Labels: Complexity: Low, Status: Needs Review, Type: Task

#72 chore: Automate Arduino Script
  extras/ARDUINO_IDE.sh
Labels: Complexity: Low, Status: Needs Review

#73 test: Add Arduino CircleCI Config
  .circleci/config.yml
  .circleci/install_arduino.sh
  .circleci/script_arduino.sh
Labels: Complexity: Low, Status: Needs Review, Test: Unit

#66 Feat: Add GTest/GMock support for ESP32
  .circleci/install_platform_io.sh
  .circleci/script_platform_io.sh
  test/api/blocks.cpp
  test/iot/gtest/gtest.h
  test/iot/test_main.cpp
  test/mocks/mock_api.h
  test/platformio.ini
Labels: Complexity: Medium, Status: Contributor Approved, Status: Needs Review

#77 chore: Add 'keywords.txt'
  keywords.txt
Labels: Complexity: Low, Status: Needs Review, Type: Task

#76 chore: Only move docs in Arduino builds
  docs/INSTALL_ARDUINO.md
  docs/INSTALL_OS.md
  docs/INSTALL_PLATFORMIO.md
  docs/cpp.md
  extras/ARDUINO_IDE.sh
Labels: Complexity: Low, Status: Needs Review, Type: Task

#78 chore: Remove STL library
  src/helpers/client_helpers.h
  src/lib/stl/array
  src/lib/stl/cassert
  src/lib/stl/cctype
  src/lib/stl/cstddef
  src/lib/stl/cstdint
  src/lib/stl/cstdio
  src/lib/stl/cstring
  src/lib/stl/details/to_string.h
  src/lib/stl/memory
Labels: Complexity: High, Status: Needs Review, Type: Task

#80 chore: bump version
  CHANGELOG.md
  library.json
  library.properties
  src/include/cpp-client/arkClient.h
Labels: Complexity: Low, Status: Needs Review, Type: Task
