Repository ArkEcosystem/cpp-client, pull requests merged in 2019-08, with the labels that each got.

#116 feat: Add debug support for VS Code
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  CMakeLists.txt
Labels: Complexity: Low, Status: Contributor Approved, Type: Feature

#114 chore: improve API query usage.
  CHANGELOG.md
  docs/cpp.md
  examples/arduino/ESP32/ESP32.ino
  examples/arduino/ESP8266/ESP8266.ino
  src/api/blocks/blocks.cpp
  src/api/delegates/delegates.cpp
  src/api/paths.cpp
  src/api/peers/peers.cpp
  src/api/transactions/transactions.cpp
  src/api/votes/votes.cpp
  src/api/wallets/wallets.cpp
  src/include/cpp-client/api/blocks/blocks.h
  src/include/cpp-client/api/delegates/delegates.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/peers/peers.h
  src/include/cpp-client/api/transactions/transactions.h
  src/include/cpp-client/api/votes/votes.h
  src/include/cpp-client/api/wallets/wallets.h
  test/api/blocks.cpp
  test/api/delegates.cpp
  test/api/paths.cpp
  test/api/peers.cpp
  test/api/transactions.cpp
  test/api/votes.cpp
  test/api/wallets.cpp
  test/mocks/mock_api.h
Labels: Complexity: High, Status: In Progress, Type: Task

#111 style: formatting and coverage
  .circleci/clang_tidy.sh
  .circleci/install_platform_io.sh
  .circleci/script_desktop.sh
  .circleci/script_platform_io.sh
  .github/stale.yml
  CHANGELOG.md
  README.md
  docs/cpp.md
  keywords.txt
  src/api/blockchain/blockchain.cpp
  src/api/blocks/blocks.cpp
  src/api/delegates/delegates.cpp
  src/api/node/node.cpp
  src/api/paths.cpp
  src/api/peers/peers.cpp
  src/api/transactions/transactions.cpp
  src/api/votes/votes.cpp
  src/api/wallets/wallets.cpp
  src/host/host.cpp
  src/http/iot/http.cpp
  src/http/iot/main.cpp
  src/http/os/http.cpp
  src/include/cpp-client/api/abstract.h
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/base.h
  src/include/cpp-client/api/blockchain/blockchain.hpp
  src/include/cpp-client/api/blocks/blocks.h
  src/include/cpp-client/api/delegates/delegates.h
  src/include/cpp-client/api/node/node.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/peers/peers.h
  src/include/cpp-client/api/transactions/transactions.h
  src/include/cpp-client/api/votes/votes.h
  src/include/cpp-client/api/wallets/wallets.h
  src/include/cpp-client/arkClient.h
  src/include/cpp-client/connection/connection.h
  src/include/cpp-client/host/host.h
  src/include/cpp-client/http/http.h
  test/api/blockchain.cpp
  test/api/blocks.cpp
  test/api/delegates.cpp
  test/api/node.cpp
  test/api/paths.cpp
  test/api/peers.cpp
  test/api/transactions.cpp
  test/api/votes.cpp
  test/api/wallets.cpp
  test/connection/connection.cpp
  test/host/host.cpp
  test/http/http.cpp
  test/mocks/mock_api.h
  test/mocks/mock_http.h
Labels: Complexity: Undetermined, Status: In Progress, Type: Standards
