Repository ArkEcosystem/cpp-client, pull requests merged in 2019-11, with the labels that each got.

#165 chore: add +x to scripts
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_arduino.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  extras/ARDUINO_IDE.sh
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#162 fix: arduino get/post
  examples/arduino/ESP32/ESP32.ino
  src/api/paths.cpp
  src/http/iot/http.cpp
  src/include/cpp-client/api/paths.h
  test/api/paths.cpp
Labels: Bounty: Tier 4, Complexity: High, Type: Bugfix

#169 build: hide cmake warning
  cmake/extern/CURL.txt.in
  cmake/extern/GTest.txt.in
Labels: Complexity: Low

#170 chore(docs): add c++11 badge
  README.md
Labels: Complexity: Low, Type: Task
