Repository ArkEcosystem/cpp-client, pull requests merged in 2019-10, with the labels that each got.

#135 ci: pass environment variables to steps
  .github/workflows/test.yml
Labels: Complexity: Low

#143 ci: setup cppcheck for codeclimate
  .codeclimate.yml
Labels: Complexity: Low

#146 ci: add coverage workflow
  .codeclimate.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  CMakeLists.txt
  README.md
  test/CMakeLists.txt
Labels: Complexity: Medium

#148 chore: merge master => develop
  .codeclimate.yml
  .github/workflows/coverage.yml
  .github/workflows/test.yml
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  CHANGELOG.md
  CMakeLists.txt
  CODEOWNERS
  README.md
  library.json
  library.properties
  test/CMakeLists.txt
Labels: Complexity: Medium, Type: Task

#151 fix: cmake warnings
  cmake/extern/CURL.txt.in
  cmake/extern/GTest.txt.in
Labels: Complexity: Low, Type: Bugfix

#149 chore: CodeClimate Improvements
  .appveyor.yml
  src/host/host.cpp
Labels: Complexity: Low, Type: Task

#153 ci: hide mocked api coverage
  .codecov.yml
Labels: Complexity: Low

#156 ci: split coverage workflows
  .github/workflows/codeclimate.yml
  .github/workflows/coverage.yml
Labels: Complexity: Low

#157 Fix ESP32 Tests
  test/platformio.ini
Labels: Complexity: Low, Status: Member Approved

#158 Enable esp8266 tests
  test/iot/test_main.cpp
  test/platformio.ini
Labels: Complexity: Medium, Status: Member Approved

#159 feat: add 2.6 endpoints
  extras/ARDUINO_IDE.sh
  src/CMakeLists.txt
  src/api/bridgechains/bridgechains.cpp
  src/api/businesses/businesses.cpp
  src/api/locks/locks.cpp
  src/api/paths.cpp
  src/api/wallets/wallets.cpp
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/bridgechains/bridgechains.h
  src/include/cpp-client/api/businesses/businesses.h
  src/include/cpp-client/api/locks/locks.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/wallets/wallets.h
  test/CMakeLists.txt
  test/api/bridgechains.cpp
  test/api/businesses.cpp
  test/api/locks.cpp
  test/api/paths.cpp
  test/api/wallets.cpp
  test/mocks/mock_api.h
Labels: Complexity: High, Status: Member Approved, Status: Needs Review, Type: Feature

#161 ci: add esp8266 arduino cli configs back
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/script_arduino.sh
Labels: Complexity: Low, Status: Member Approved

#163 feat: disable wifi on esp8266 during tests
  test/iot/platform.hpp
  test/iot/test_main.cpp
  test/platformio.ini
Labels: Complexity: Low, Status: Member Approved, Type: Feature
