Repository ArkEcosystem/cpp-client, pull requests merged in 2019-07, with the labels that each got.

#98 fix(manifest): Correct Supported Platforms
  library.json
Labels: Complexity: Low, Type: Bugfix

#99 chore(manifest): add supported platforms arduino
  library.json
Labels: Complexity: Low, Type: Task

#102 fix: refactor legacy
  src/include/cpp-client/api/abstract.h
  src/include/cpp-client/http/http.h
  test/http/http.cpp
  test/mocks/mock_api.h
  test/mocks/mock_http.h
Labels: Complexity: Medium, Type: Bugfix

#100 refactor: remove version argument remains
  docs/cpp.md
  examples/arduino/ESP32/ESP32.ino
  examples/arduino/ESP8266/ESP8266.ino
  examples/cmake_example/main.cpp
  examples/platformio_example/src/main.ino
  src/http/iot/http.cpp
  src/http/os/http.cpp
  src/include/cpp-client/api/abstract.h
  src/include/cpp-client/api/api.h
  src/include/cpp-client/http/http.h
  test/api/blocks.cpp
  test/api/delegates.cpp
  test/api/node.cpp
  test/api/peers.cpp
  test/api/transactions.cpp
  test/api/votes.cpp
  test/api/wallets.cpp
  test/connection/connection.cpp
  test/http/http.cpp
  test/mocks/mock_api.h
  test/mocks/mock_http.h
Labels: Complexity: High, Type: Refactor

#104 feat(api): add blockchain endpoint
  CHANGELOG.md
  README.md
  docs/INSTALL_ARDUINO.md
  docs/cpp.md
  examples/arduino/ESP32/ESP32.ino
  examples/arduino/ESP8266/ESP8266.ino
  examples/cmake_example/main.cpp
  examples/platformio_example/src/main.ino
  extras/ARDUINO_IDE.sh
  src/CMakeLists.txt
  src/api/blockchain/blockchain.cpp
  src/api/paths.cpp
  src/http/iot/http.cpp
  src/http/os/http.cpp
  src/include/cpp-client/api/abstract.h
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/blockchain/blockchain.hpp
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/http/http.h
  test/CMakeLists.txt
  test/api/blockchain.cpp
  test/api/blocks.cpp
  test/api/delegates.cpp
  test/api/node.cpp
  test/api/peers.cpp
  test/api/transactions.cpp
  test/api/votes.cpp
  test/api/wallets.cpp
  test/connection/connection.cpp
  test/http/http.cpp
  test/mocks/mock_api.h
  test/mocks/mock_http.h
Labels: Complexity: High, Type: Feature

#101 fix: always send application/json as content-type
  src/http/iot/http.cpp
  src/http/os/http.cpp
Labels: Complexity: Low, Type: Bugfix

#106 test(blockchain): add missing paths test
  test/api/paths.cpp
Labels: Complexity: Low, Test: Unit

#105 chore(develop): update from master
  src/http/iot/http.cpp
  src/http/os/http.cpp
  test/api/wallets.cpp
Labels: Complexity: Low, Type: Task

#108 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#109 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task
