Repository ArkEcosystem/cpp-client, pull requests merged in 2019-09, with the labels that each got.

#120 chore: Add appveyor support
  .appveyor
  .appveyor.yml
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Task

#122 feat: crypto endpoint
  src/api/node/node.cpp
  src/api/paths.cpp
  src/include/cpp-client/api/node/node.h
  src/include/cpp-client/api/paths.h
  test/api/node.cpp
  test/api/paths.cpp
  test/mocks/mock_api.h
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Feature

#119 chore: Add support for VS2019
  CMakeSettings.json
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Task

#129 ci: setup github action workflow for testing
  .circleci/config.yml
  .github/workflows/test.yml
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_arduino.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
Labels: Complexity: Medium, Status: Needs Review

#127 feat: add missing api endpoints
  extras/ARDUINO_IDE.sh
  src/CMakeLists.txt
  src/api/node/node.cpp
  src/api/paths.cpp
  src/api/rounds/rounds.cpp
  src/api/transactions/transactions.cpp
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/node/node.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/rounds/rounds.h
  src/include/cpp-client/api/transactions/transactions.h
  test/CMakeLists.txt
  test/api/blocks.cpp
  test/api/node.cpp
  test/api/paths.cpp
  test/api/rounds.cpp
  test/api/transactions.cpp
  test/mocks/mock_api.h
Labels: Complexity: Medium, Status: Contributor Approved, Type: Feature

#132 ci: update arduino triggers
  .github/workflows/test.yml
  .github/workflows/test/script_arduino.sh
Labels: Complexity: Low

#126 Bug: fix windows curl
  .appveyor.yml
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Complexity: Low, Status: Contributor Approved
