Repository ArkEcosystem/cpp-client, pull requests merged in 2019-05, with the labels that each got.

#85 test: API Empty TX Object Response
  CHANGELOG.md
  test/http/http.cpp
Labels: Complexity: Low, Test: Unit

#86 Fixed misspellings
  examples/arduino/ESP32/ESP32.ino
  examples/arduino/ESP8266/ESP8266.ino
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved

#92 style: Improve Formatting and Maintainability
  .circleci/clang_tidy.sh
  CHANGELOG.md
  extras/ARDUINO_IDE.sh
  src/api/blocks/blocks.cpp
  src/api/delegates/delegates.cpp
  src/api/node/node.cpp
  src/api/paths.cpp
  src/api/peers/peers.cpp
  src/api/transactions/transactions.cpp
  src/api/votes/votes.cpp
  src/api/wallets/wallets.cpp
  src/host/host.cpp
  src/include/cpp-client/api/abstract.h
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/base.h
  src/include/cpp-client/api/blocks/blocks.h
  src/include/cpp-client/api/delegates/delegates.h
  src/include/cpp-client/api/node/node.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/peers/peers.h
  src/include/cpp-client/api/transactions/transactions.h
  src/include/cpp-client/api/votes/votes.h
  src/include/cpp-client/api/wallets/wallets.h
  src/include/cpp-client/connection/connection.h
  src/include/cpp-client/host/host.h
  src/include/cpp-client/http/http.h
  test/api/blocks.cpp
  test/api/delegates.cpp
  test/api/node.cpp
  test/api/paths.cpp
  test/api/peers.cpp
  test/api/transactions.cpp
  test/api/votes.cpp
  test/api/wallets.cpp
  test/host/host.cpp
  test/http/http.cpp
  test/iot/test_main.cpp
  test/mocks/mock_api.h
  test/mocks/mock_http.h
Labels: Complexity: Undetermined, Type: Standards

#93 test: increase coverage
  CHANGELOG.md
  src/host/host.cpp
  src/include/cpp-client/host/host.h
  test/api/paths.cpp
  test/connection/connection.cpp
  test/host/host.cpp
  test/http/http.cpp
Labels: Complexity: Medium, Type: Task

#95 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#97 chore: use correct field separator in keywords.txt
  keywords.txt
Labels: Complexity: Low, Status: Contributor Approved
