Repository ArkEcosystem/cpp-client, pull requests merged in 2020-02, with the labels that each got.

#173 release: 1.4.0
  .appveyor.yml
  .codecov.yml
  .github/workflows/codeclimate.yml
  .github/workflows/coverage.yml
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_arduino.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_arduino.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  CHANGELOG.md
  cmake/extern/CURL.txt.in
  cmake/extern/GTest.txt.in
  examples/arduino/ESP32/ESP32.ino
  extras/ARDUINO_IDE.sh
  library.json
  library.properties
  src/CMakeLists.txt
  src/api/bridgechains/bridgechains.cpp
  src/api/businesses/businesses.cpp
  src/api/locks/locks.cpp
  src/api/paths.cpp
  src/api/wallets/wallets.cpp
  src/host/host.cpp
  src/http/iot/http.cpp
  src/include/cpp-client/api/api.h
  src/include/cpp-client/api/bridgechains/bridgechains.h
  src/include/cpp-client/api/businesses/businesses.h
  src/include/cpp-client/api/locks/locks.h
  src/include/cpp-client/api/paths.h
  src/include/cpp-client/api/wallets/wallets.h
  test/CMakeLists.txt
  test/api/bridgechains.cpp
  test/api/businesses.cpp
  test/api/locks.cpp
  test/api/paths.cpp
  test/api/wallets.cpp
  test/iot/platform.hpp
  test/iot/test_main.cpp
  test/mocks/mock_api.h
  test/platformio.ini
Labels: Complexity: Medium, Type: Release

#174 release: 1.4.0-arduino
  CHANGELOG.md
  CODEOWNERS
  README.md
  examples/ESP32/ESP32.ino
  extras/ARDUINO_IDE.sh
  library.json
  library.properties
  platformio.ini
  src/api/api.h
  src/api/bridgechains/bridgechains.cpp
  src/api/bridgechains/bridgechains.h
  src/api/businesses/businesses.cpp
  src/api/businesses/businesses.h
  src/api/locks/locks.cpp
  src/api/locks/locks.h
  src/api/paths.cpp
  src/api/paths.h
  src/api/wallets/wallets.cpp
  src/api/wallets/wallets.h
  src/host/host.cpp
  src/http/http.cpp
Labels: Complexity: Medium, Type: Release

#179 ci: remove codeclimate
  .codeclimate.yml
  .github/workflows/codeclimate.yml
Labels: Complexity: Low

#178 docs(changelog): separate platforms [arduino]
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#177 docs(changelog): separate platforms
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#176 chore(build): improve as dependency
  cmake/External.cmake
  src/CMakeLists.txt
Labels: Complexity: Low, Type: Task

#180 ci(cov): add/hit missing tests
  src/api/paths.cpp
  test/api/paths.cpp
Labels: Complexity: Medium

#182 ci: maintenance
  .codacy.yml
  .github/workflows/test/clang_format.sh
  .github/workflows/test/clang_tidy.sh
  .github/workflows/test/install_platform_io.sh
  .github/workflows/test/script_desktop.sh
  .github/workflows/test/script_platform_io.sh
  build.sh
  run_tests.sh
  test/iot/platform.hpp
Labels: Complexity: Low

#183 feat: add methods for first and last block
  src/api/blocks/blocks.cpp
  src/api/paths.cpp
  src/include/cpp-client/api/blocks/blocks.h
  src/include/cpp-client/api/paths.h
  test/api/blocks.cpp
  test/api/paths.cpp
  test/mocks/mock_api.h
Labels: Complexity: Medium, Status: Member Approved, Type: Feature

#185 feat: add methods for first and last block [arduino]
  src/api/blocks/blocks.cpp
  src/api/blocks/blocks.h
  src/api/paths.cpp
  src/api/paths.h
Labels: Complexity: Low, Type: Feature

#184 chore(paths): extract query pattern [arduino]
  src/api/paths.cpp
Labels: Complexity: Medium, Type: Task
